# Generated by Django 6.0.3 on 2026-03-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_financeentry_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeentry',
            name='concept',
            field=models.CharField(choices=[('sale', 'Venta'), ('purchase', 'Compra'), ('capital_payment', 'Abono a capital'), ('layaway_payment', 'Cobro de apartado'), ('transfer', 'Transferencia'), ('expense', 'Gasto')], max_length=20),
        ),
    ]
