# Generated by Django 6.0.3 on 2026-03-26 13:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventoryitem_options_and_more'),
        ('sales', '0002_sale_core_alignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('msi', 'MSI'), ('consignment', 'Consigna')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_records', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_channel',
            field=models.CharField(choices=[('marketplace', 'Marketplace'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('direct', 'Directo'), ('other', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
