# Generated by Django 6.0.3 on 2026-03-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="instagram_handle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
