# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_alter_client_created_by_alter_client_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
